[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
derive_more = "0.99.17"
ecow = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.parser]
path = "../parser"
